Changes for script manageability
Dynamically build country list fixed (Andy)
Made most everything functions so that they could be called as needed (flexibility and maintainability).

diff --git a/rtd-nordvpn b/rtd-nordvpn
--- a/rtd-nordvpn
+++ b/rtd-nordvpn
@@ -1,25 +1,25 @@
 #!/bin/bash
 #
-#::             RTD Ubuntu + derivatives configuration and setup script
+#::             RTD Ubuntu + derivatives and Fedora/Centos configuration and setup script
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#:: Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
+#:: Author(s):   	SLS, Andy.  Sweden, Australia
 RTD_Version="1.00"
 #::
 #::
-#::	Purpose: - The purpose of the script is to setup nordvpn if required, and connect. 
-#::		 - You must setup an account with the VPN vendor to use the service.
+#::	Purpose: 	- The purpose of the script is to setup nordvpn if required, display a list of countries,and connect.
+#::		 	- You must setup an account with the VPN vendor to use the service.
 #::
-#::	Dependencies:
-#::	  _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems. 
+#::	Dependencies: 	None required up front. You must be running linux that uses either the RPM or DEB package
+#::	 		managment software for the automatic software install to work as well as dialog or whiptial for menus.
 #::
-#::
-#::
+#::	License: 	This software is provided under the GPL (General Public License v3.0).
+#::			This software is provided as is with no warranty.
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-	
+
 
 
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -28,10 +28,12 @@ RTD_Version="1.00"
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
+# Set where to find the installable files
 NORDVPN_DEB="https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb"
 NORDVPN_RPM="https://repo.nordvpn.com/yum/nordvpn/centos/noarch/Packages/n/nordvpn-release-1.0.0-1.noarch.rpm"
 
-
+# Set the background colors
+export NEWT_COLORS='root=,gray '
 
 
 
@@ -41,53 +43,17 @@ NORDVPN_RPM="https://repo.nordvpn.com/yum/nordvpn/centos/noarch/Packages/n/nordv
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-# Set some basic preferences... 
+# Discover my own script name...
 me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
-export NEWT_COLORS='root=,gray '
-
-# Notify the user that some things may need to be done if this is the first time the script is run.
-if [ ! -f ~/.config/rtd-nordvpn-firstrun.ok ]; then 
-	whiptail --title "RTD Nordvpn Starter: First Run Dialog" --msgbox "	This appears to be the first time that $me is run. Please note that you 
-	may be prompted to allow me to do some things. I will need to:
-
-	- make sure the _rtd_functions (instructions how I should do things) are present
-	- make sure that the Nordvpn client is installed
-	
-	Press [ENTER] to continue" 0 110
-	mkdir -p ~/.config && touch ~/.config/rtd-nordvpn-firstrun.ok
-fi
-
-# If the RTD functions file is present use it, otherwise download a new copy of it and use this. 
-if [ -f ~/bin/_rtd_functions ]; then 
-	source ~/bin/_rtd_functions
-else 
-	if [ -f /opt/rtd/scripts/_rtd_functions ]; then 
-		source /opt/rtd/scripts/_rtd_functions
-	else 
-		echo RTD Functions not found... 
-		if (whiptail  --title "RTD Nordvpn Starter: Get Parts" --yesno "For this tool to run correctly I need to download some software from the internet. Is this OK?" 8 78); then
-			echo "OK Thank you. Geting the required scrpt lirary file "RTD_FUNCTIONS"" 
-			sudo mkdir -p /opt/rtd/scripts
-			sudo wget -q https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions -P /opt/rtd/scripts/
-			source /opt/rtd/scripts/_rtd_functions
-		else
-			echo "You selected No, exit status was $?."
-			exit
-		fi
-
-	fi
-fi
-
-echo "RTD_FUNCTIONS = $RTDFUNCTIONS"
-if [ $RTDFUNCTIONS -eq 1 ]; then
-        echo RTD functions confirmed loaded!
-      else
-        echo RTD functions NOT loaded!
-	echo Please make sure that you are connected to the internet and that sudo and wget are installed.
-	exit 1
-fi
+set_colors () { YELLOW="\033[1;33m" RED="\033[0;31m" ENDCOLOR="\033[0m" GREEN="\033[0;32m" BLUE="\033[0;34m" ; }
+set_colors
+export _branding="NordVPN"
 
 
+clear
+echo ---------------------------------------------------------------------------
+echo $_branding : Stay safe
+echo ---------------------------------------------------------------------------
 
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
@@ -95,23 +61,105 @@ fi
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
+check_menu_availability () {
+	# First discover what menu system is installed. Some systems use "dialog" and
+	# other systems use whiptail for the terminal to show menus and dialogs.
+	# If nothing is found, then make sure it is available before continuing.
+	if hash whiptail >/dev/null ; then
+		export rtd_menu=whiptail
+	elif hash dialog >/dev/null ; then
+		export rtd_menu=dialog
+	else
+		err_no_menu_system_found
+	fi
+
+}
+
+err_no_menu_system_found () {
+	echo -e "$RED There is no way to display menus on this system $ENDCOLOR"
+	echo -e "This is required to display the chices of countries..."
+	echo -e "$YELLOW May I attepmpt to install this ability to your system? $ENDCOLOR"
+	read -p "Add software: (y/n)?" choice
+	case "$choice" in
+	  y|Y ) install_software whiptail ;;
+	  n|N ) err_no_menu_system_available ;;
+	  * ) echo "Invalid Selection" && err_no_menu_system_found ;;
+	esac
+
+}
+
+install_software () {
+	if hash pkcon 2>/dev/null; then
+		pkcon -y  install $@
+	elif hash yum 2>/dev/null; then
+		yum -y  install $@
+	elif hash zypper 2>/dev/null; then
+		zypper install -y $@
+	elif hash apt-get 2>/dev/null; then
+		export DEBIAN_FRONTEND=noninteractive
+		apt-get -y -qq --allow-change-held-packages --ignore-missing install $@
+	else
+		echo -e $YELLOW "This system does not seem to have a software managment system" $ENDCOLOR
+		err_no_menu_system_available
+		_cleanup
+		exit 1
+	fi
+}
+
+
+err_nordvpn_install () {
+	$rtd_menu --title "$_branding helper: PROBLEM" --msgbox "	I was not able to install Nordvn for you. Please do it manually and try again" 0 110
+	_cleanup
+	exit 1
+}
+
+
+err_no_menu_system_available () {
+	echo "There is no menu or dialog software installed on this system..."
+	echo "If you want to use $me you must ensure that whiptail or dialog is installed."
+	read -p Press [ENTER] to exit...
+	_cleanup
+	exit 1
+}
+
+
+check_if_first_run () {
+	# Notify the user that some things may need to be done if this is the first time the script is run.
+	if [ ! -f ~/.config/rtd-nordvpn-firstrun.ok ]; then
+		$rtd_menu --title "$_branding helper: First Run Dialog" --msgbox "	This appears to be the first time that $me is run. Please note that you
+		may be prompted to allow me to do some things. I may need to:
+
+		- make sure that the Nordvpn client is installed
+
+		Press [ENTER] to continue" 0 110
+		mkdir -p ~/.config && touch ~/.config/rtd-nordvpn-firstrun.ok
+	fi
+}
+
+
+watch_vpn_connection () {
+	status_cycle () {
+		echo ---------------------------------------------------------------------------
+		echo $_branding Connected $(date)
+		echo ---------------------------------------------------------------------------
+		nordvpn status
+	}
+	export -f status_cycle
+	watch -t -x bash --pretty-print -c status_cycle
+}
+
+
+_cleanup () {
+	_branding=
+}
+
 
 select_country_to_tunnel_to () {
-
-	while true; do
+	local -a countries_array=( '' '' $(nordvpn countries | tr -c '[:alnum:][:blank:]_' ' ') )
+	local countries_for_rtdmenu=$( for ((i=2;i<${#countries_array[@]};i++)) ; do echo $i ${countries_array[$i]} ; done )
+	while : ; do
 		exec 3>&1
-		selection=$(whiptail \
-		--ok-button "Connect VPN" \
-		--cancel-button "Cancel/Disconnect VPN" \
-		--title "Nordvpn Country Selector" \
-		--menu "" 0 110 0 \
-		"1" "Nearest server" \
-		"2" "Denmark" \
-		"3" "Iceland" \
-		"4" "Luxembourg" \
-		"5" "France" \
-		"6" "Germany" \
-		2>&1 1>&3)
+		selection=$( $rtd_menu	--fb --ok-button "Connect VPN" --cancel-button "Cancel/Disconnect VPN" --title "$_branding Country Selector" --menu "" 0 110 0 "1" "Nearest server" $countries_for_rtdmenu 2>&1 1>&3)
 		exit_status=$?
 		exec 3>&-
 
@@ -119,6 +167,7 @@ select_country_to_tunnel_to () {
 			1)
 				clear
 				nordvpn disconnect
+				echo -e "$YELLOW Thankyou for being security concious... $ENDCOLOR "
 				exit
 			;;
 			255)
@@ -136,26 +185,11 @@ select_country_to_tunnel_to () {
 		clear
 		echo "Program terminated by user..."
 		;;
-		1 )
-		nordvpn connect && watch nordvpn status
-		;;
-		2 )
-		nordvpn connect Denmark && watch nordvpn status
-		;;
-		3 )
-		nordvpn connect Iceland && watch nordvpn status
-		;;
-		4 )
-		nordvpn connect Luxembourg && watch nordvpn status
-		;;
-		5 )	
-		nordvpn connect France && watch nordvpn status
-		;;
-		6 )	
-		nordvpn connect Germany && watch nordvpn status
+		* )
+		nordvpn connect ${countries_array[$selection]} && watch_vpn_connection
 		;;
 		esac
-	done   
+	done
 }
 
 
@@ -163,23 +197,25 @@ select_country_to_tunnel_to () {
 run_nordvpn() {
 	if hash nordvpn 2>/dev/null; then
 		select_country_to_tunnel_to
-		
+
 	else
-		if (whiptail --backtitle "$BRANDING" --title "RTD Nordvpn Starter: Get VPN" --yesno "Nordvpn is not installed... I need to download it from the internet. Is this OK?" 8 78); then
-			echo "OK Thank you. Geting Nordvpn from the website..." 
+		if ($rtd_menu --title "$_branding helper: Get VPN" --yesno "Nordvpn is not installed... I need to download it from the internet. Is this OK?" 8 78); then
+			echo "OK Thank you. Geting Nordvpn from the website..."
 			if hash rpm 2>/dev/null; then
-				sudo rpm -ivh $NORDVPN_RPM || sudo yum update -y 
-				sudo yum install nordvpn && select_country_to_tunnel_to
-			elif hash apt 2>/dev/null; then 
-				sudo wget -q $NORDVPN_DEB && sudo dpkg -i ./nordvpn-release_1.0.0_all.deb
-				sudo apt -f install 
+				sudo rpm -ivh $NORDVPN_RPM || sudo yum update -y
+				sudo yum install nordvpn && select_country_to_tunnel_to || err_nordvpn_install
+			elif hash apt 2>/dev/null; then
+				sudo wget -q $NORDVPN_DEB && sudo dpkg -i ./nordvpn-release_1.0.0_all.deb && sudo rm ./nordvpn-release_1.0.0_all.deb
+				sudo apt -f install
 				sudo apt update
-				sudo apt -y install nordvpn && select_country_to_tunnel_to
-			else 
-			    whiptail --title "RTD Nordvpn Starter: PROBLEM" --msgbox "	I was not able to install Nordvn for you. Please do it manually and try again" 0 110
+				sudo apt -y install nordvpn
+				sudo apt -f install && select_country_to_tunnel_to || err_nordvpn_install
+			else
+				err_nordvpn_install
 			fi
 		else
-			echo "You selected No, exit status was $?."
+			$rtd_menu --title "$_branding helper: Get VPN" --msgbox "Nordvpn was not installed... Without the VPN software I cannot continue. My appologies, but I must exit." 8 78
+			_cleanup
 			exit
 		fi
 
@@ -195,5 +231,6 @@ run_nordvpn() {
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
 
-
+check_menu_availability
+check_if_first_run
 run_nordvpn
